ext.foldProfile = [
    versionName: "0.119.0-fold.4",
    versionCode: 2026082904,
    applicationLabel: "Termux Fold",
    packageVariant: "apt-android-7",
    supportedAbis: ["arm64-v8a"].asImmutable()
].asImmutable()

buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.13.2"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}
